#!/bin/bash

# Replace with your actual domain
DOMAIN="ag-weli.tech"

# Backend server IP addresses
SERVER1_IP="100.25.200.118"
SERVER2_IP="54.237.88.4"

# Install HAProxy
sudo apt-get update
sudo apt-get install -y haproxy

# Install Certbot and obtain SSL certificate
sudo apt-get install -y certbot python3-certbot-nginx
sudo certbot certonly --standalone -d www.$DOMAIN

# Create HAProxy configuration file
cat <<EOF | sudo tee /etc/haproxy/haproxy.cfg
global
    log /dev/log local0
    log /dev/log local1 notice
    chroot /var/lib/haproxy
    stats socket /run/haproxy/admin.sock mode 660 level admin expose-fd listeners
    stats timeout 30s
    user haproxy
    group haproxy
    daemon

defaults
    log global
    mode http
    option httplog
    option dontlognull
    timeout connect 5000
    timeout client 50000
    timeout server 50000

frontend http-in
    bind *:80
    bind *:443 ssl crt /etc/letsencrypt/live/www.$DOMAIN/fullchain.pem
    reqadd X-Forwarded-Proto:\ https
    default_backend backend_servers

backend backend_servers
    mode http
    server server1 $SERVER1_IP:80 check
    server server2 $SERVER2_IP:80 check

EOF

# Restart HAProxy
sudo service haproxy restart

# Test your setup
curl -sI https://www.$DOMAIN
curl https://www.$DOMAIN

# Optionally, set up a cron job to renew SSL certificates automatically
# crontab -e
# Add the following line to run renewal checks twice a day:
# 0 */12 * * * /usr/bin/certbot renew --quiet

