#!/usr/bin/env bash
# Installs Nginx with the following configurations:
# - Listens on port 80.
# - Returns a page containing "Holberton School" when queried
#   at the root with a curl GET request.

# Update package repositories
apt-get update

# Install Nginx
apt-get install -y nginx

# Create the HTML directory and index.html file
mkdir -p /etc/nginx/html
echo "Hello World!" > /etc/nginx/html/index.html

# Create the Nginx default server block configuration
printf %s "server {
     listen      80 default_server;
     listen      [::]:80 default_server;
     root        /etc/nginx/html;
     index       index.html index.htm;
}
" > /etc/nginx/sites-available/default

# Restart the Nginx service to apply changes
service nginx restart


